#!/bin/bash

INPUT_FILE=$1
commitMsg=`head -n1 $INPUT_FILE`

keywords=('[F|f]eat' '[F|f]ix' '[P|p]erf' '[B|b]uild' '[C|c]i' '[D|d]ocs' '[R|r]efactor' '[S|s]tyle' '[T|t]est')
kn=('feat' 'fix' 'perf' 'build' 'ci' 'docs' 'refactor' 'style' 'test')

PALETTE_RED='\033[0;31m'
PALLETE_NC='\033[0m'
PALETTE_GREEN='\e[32m'

for key in ${keywords[@]}; do
  if [[ $commitMsg == $key* ]];
  then
    echo -e -n "\U2705"
    echo -e " The confirmation ${PALETTE_GREEN} message is valid ${PALLETE_NC}. You can now push..."
    exit 0
  fi
done

echo -e -n "\U274C"
echo " Commit message is invalid."
echo -e "The ${PALETTE_RED} commit message ${PALLETE_NC} should start with one of the following keywords: ${PALETTE_GREEN} ${kn[*]}"

exit 1
