#!/bin/bash

commitMsg=$(git log -1 --pretty=%B)

keywords=('[F|f]eat' '[F|f]ix' '[P|p]erf' '[B|b]uild' '[C|c]i' '[D|d]ocs' '[R|r]efactor' '[S|s]tyle' '[T|t]est')
kn=('feat' 'fix' 'perf' 'build' 'ci' 'docs' 'refactor' 'style' 'test')

PALETTE_RED='\033[0;31m'
PALLETE_NC='\033[0m'
PALETTE_GREEN='\e[32m'

for key in ${keywords[@]}; do
  if [[ $commitMsg == $key* ]];
  then
    echo -e -n "\U2705"
    echo " The commit message is valid. Doing push..."
    exit 0
  fi
done

echo -e -n "\U274C"
echo " Commit message is invalid."
echo -e "Use ${PALETTE_RED}git commit --amend${PALLETE_NC} to change the commit message.\n"
echo -e "The commit message should start with one of the following keywords: ${PALETTE_GREEN} ${kn[*]}"

exit 1
